apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-vpc-block-csi-driver-operator
  namespace: openshift-cluster-csi-drivers
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-vpc-block-csi-driver-operator
  strategy: {}
  template:
    metadata:
      labels:
        name: ibm-vpc-block-csi-driver-operator
      annotations:
        openshift.io/required-scc: restricted-v2
    spec:
      containers:
      - args:
        - start
        env:
        - name: DRIVER_IMAGE
          value: ${DRIVER_IMAGE}
        - name: PROVISIONER_IMAGE
          value: ${PROVISIONER_IMAGE}
        - name: ATTACHER_IMAGE
          value: ${ATTACHER_IMAGE}
        - name: NODE_DRIVER_REGISTRAR_IMAGE
          value: ${NODE_DRIVER_REGISTRAR_IMAGE}
        - name: LIVENESS_PROBE_IMAGE
          value: ${LIVENESS_PROBE_IMAGE}
        - name: RESIZER_IMAGE
          value: ${RESIZER_IMAGE}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: quay.io/ocs-roks-team/origin-ibm-vpc-block-csi-driver-operator:latest
        imagePullPolicy: Always
        name: ibm-vpc-block-csi-driver-operator
      priorityClassName: system-cluster-critical
      serviceAccountName: ibm-vpc-block-csi-driver-operator
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: "NoSchedule"
